# Generated by Django 5.1.1 on 2024-09-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ussr_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('User_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('insta_name', models.CharField(max_length=50)),
                ('faceboook_name', models.CharField(max_length=50)),
            ],
        ),
    ]
