# Generated by Django 5.1.1 on 2024-09-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faceboook_name',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='insta_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
