# Generated by Django 5.1.1 on 2024-09-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_bio_alter_user_faceboook_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ussr_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='faceboook_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
