# Generated by Django 5.1.1 on 2024-09-16 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_ussr_id_user_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Nature', 'Nature'), ('Travel', 'Travel'), ('Animal', 'Animal'), ('Wallpaper', 'Wallpaper'), ('Art and Culture', 'Art and Culture'), ('India', 'India'), ('Anime', 'Anime'), ('Flower', 'Flower'), ('City', 'City'), ('Texture and Patterns', 'Texture and Patterns'), ('Prople', 'Prople'), ('Film', 'Film'), ('Fashion', 'Fashion'), ('History', 'History')], max_length=100)),
                ('tags', models.TextField(blank=True)),
                ('added', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
