# Generated by Django 5.1.1 on 2024-09-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
