# Generated by Django 5.1.1 on 2024-09-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_posts_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('nature', 'nature'), ('travel', 'travel'), ('animal', 'animal'), ('wallpaper', 'wallpaper'), ('india', 'india'), ('anime', 'anime'), ('flower', 'flower'), ('city', 'city'), ('prople', 'prople'), ('film', 'film'), ('fashion', 'fashion'), ('history', 'history')], max_length=100),
        ),
    ]
